bracketSpacing: true
plugins:
  - '@trivago/prettier-plugin-sort-imports'
printWidth: 120
proseWrap: 'always'
singleQuote: true
tabWidth: 2
trailingComma: 'all'

overrides:
  - files: '*.ts'
    options:
      importOrder: ['<THIRD_PARTY_MODULES>', '^[./]']
      importOrderParserPlugins: ['typescript']
      importOrderSeparation: true
      importOrderSortSpecifiers: true
      parser: 'typescript'
